SOURCES += \
	./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_PrivFunc.cpp	\
	./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivCoreFunc.cpp	\
	./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_PrivFunc.cpp	\
	./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivCoreFunc.cpp	\
	./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_PrivFunc.cpp	\
	./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivCoreFunc.cpp	\
	./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_PrivFunc.cpp	\
	./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivCoreFunc.cpp	\
	./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_PrivFunc.cpp	\
	./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivCoreFunc.cpp	\
	./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_PrivFunc.cpp	\
	./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivCoreFunc.cpp	\
	./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_PrivFunc.cpp	\
	./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivCoreFunc.cpp	\
	./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_PrivFunc.cpp	\
	./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivCoreFunc.cpp	\
	./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_PrivFunc.cpp	\
	./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivCoreFunc.cpp	\
	./Sensor/Laser/SensorTimer/Edit/SensorTimer_Sensor_Laser_PrivFunc.cpp	\
	./Sensor/Laser/SensorTimer/NoEdit/SensorTimer_Sensor_Laser_PrivCoreFunc.cpp	\
	./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_PrivFunc.cpp	\
	./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivCoreFunc.cpp	\
	./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_PrivFunc.cpp	\
	./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivCoreFunc.cpp	

HEADERS += \
	./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_ParamsData.h	\
	./Sensor/Camera/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Camera_Vars.h	\
	./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivFunc.h	\
	./Sensor/Camera/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Camera_PrivCoreFunc.h	\
	./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_ParamsData.h	\
	./Sensor/Camera/VisualizationMono/Edit/VisualizationMono_Sensor_Camera_Vars.h	\
	./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivFunc.h	\
	./Sensor/Camera/VisualizationMono/NoEdit/VisualizationMono_Sensor_Camera_PrivCoreFunc.h	\
	./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_ParamsData.h	\
	./Sensor/Camera/StorageMono/Edit/StorageMono_Sensor_Camera_Vars.h	\
	./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivFunc.h	\
	./Sensor/Camera/StorageMono/NoEdit/StorageMono_Sensor_Camera_PrivCoreFunc.h	\
	./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_ParamsData.h	\
	./Sensor/Joystick/SensorInternalEvent/Edit/SensorInternalEvent_Sensor_Joystick_Vars.h	\
	./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivFunc.h	\
	./Sensor/Joystick/SensorInternalEvent/NoEdit/SensorInternalEvent_Sensor_Joystick_PrivCoreFunc.h	\
	./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_ParamsData.h	\
	./Sensor/Joystick/VisualizationMono/Edit/VisualizationMono_Sensor_Joystick_Vars.h	\
	./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivFunc.h	\
	./Sensor/Joystick/VisualizationMono/NoEdit/VisualizationMono_Sensor_Joystick_PrivCoreFunc.h	\
	./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_ParamsData.h	\
	./Sensor/Joystick/StorageMono/Edit/StorageMono_Sensor_Joystick_Vars.h	\
	./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivFunc.h	\
	./Sensor/Joystick/StorageMono/NoEdit/StorageMono_Sensor_Joystick_PrivCoreFunc.h	\
	./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_ParamsData.h	\
	./Sensor/stm32comm/SourceDrainMono/Edit/SourceDrainMono_Sensor_stm32comm_Vars.h	\
	./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivFunc.h	\
	./Sensor/stm32comm/SourceDrainMono/NoEdit/SourceDrainMono_Sensor_stm32comm_PrivCoreFunc.h	\
	./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_ParamsData.h	\
	./Sensor/stm32comm/StorageMono/Edit/StorageMono_Sensor_stm32comm_Vars.h	\
	./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivFunc.h	\
	./Sensor/stm32comm/StorageMono/NoEdit/StorageMono_Sensor_stm32comm_PrivCoreFunc.h	\
	./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_ParamsData.h	\
	./Sensor/stm32comm/VisualizationMono/Edit/VisualizationMono_Sensor_stm32comm_Vars.h	\
	./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivFunc.h	\
	./Sensor/stm32comm/VisualizationMono/NoEdit/VisualizationMono_Sensor_stm32comm_PrivCoreFunc.h	\
	./Sensor/Laser/SensorTimer/Edit/SensorTimer_Sensor_Laser_ParamsData.h	\
	./Sensor/Laser/SensorTimer/Edit/SensorTimer_Sensor_Laser_Vars.h	\
	./Sensor/Laser/SensorTimer/NoEdit/SensorTimer_Sensor_Laser_PrivFunc.h	\
	./Sensor/Laser/SensorTimer/NoEdit/SensorTimer_Sensor_Laser_PrivCoreFunc.h	\
	./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_ParamsData.h	\
	./Sensor/Laser/StorageMono/Edit/StorageMono_Sensor_Laser_Vars.h	\
	./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivFunc.h	\
	./Sensor/Laser/StorageMono/NoEdit/StorageMono_Sensor_Laser_PrivCoreFunc.h	\
	./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_ParamsData.h	\
	./Sensor/Laser/VisualizationMono/Edit/VisualizationMono_Sensor_Laser_Vars.h	\
	./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivFunc.h	\
	./Sensor/Laser/VisualizationMono/NoEdit/VisualizationMono_Sensor_Laser_PrivCoreFunc.h	

